Add ABP configuration to TTI devices
TheThingsNetwork/lorawan-devices pull request #252
Opened 2021-07-08 18:29 UTC by Jaime-Trinidad

#### Summary

Add ABP configuration to avoid break routing when using ABP for EU868 #110 

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

2021-07-12 08:08 UTC, htdvisser reviewed
I'm not the expert on these devices (otherwise I'd have done it myself), but this doesn't look quite right to me yet.

2021-07-12 08:08 UTC, htdvisser commented on vendor/the-things-products/the-things-uno-abp.yaml
> +name: The Things Uno ABP
Shouldn't this just be a different profile for the existing device?

2021-07-12 08:09 UTC, htdvisser commented
@johanstokking since you contributed quite a lot to these Arduino SDKs I think it's better if you reviewed this.

2021-07-13 07:42 UTC, johanstokking requested changes
Agreed with @htdvisser's points:

1. There is no ABP example for The Things Node
2. The Things Uno has an ABP example (`SendABP`: https://github.com/TheThingsNetwork/arduino-device-lib/blob/ea60c59a726d4147aad878a928da5c8baa7faa50/examples/SendABP/SendABP.ino), and that should simply be a firmware version with a profile. This should be under the `the-things-uno` end device
3. RX1 delay is 1 second

2021-07-13 10:27 UTC, Jaime-Trinidad commented
I fixed files:

1. I delete ABP on Generic Node.
2. Added a firmware version with a profile in The Things Uno file.
3. Fixed RX1 delay to 1 second.

2021-07-14 08:03 UTC, johanstokking requested changes

2021-07-14 08:03 UTC, johanstokking commented on vendor/the-things-products/the-things-uno.yaml
> +    numeric: 2
The hardware is the same

2021-07-14 09:36 UTC, Jaime-Trinidad commented on vendor/the-things-products/the-things-uno.yaml
> +    numeric: 2
ok, now is fixed, same hardware version

2021-07-14 16:14 UTC, johanstokking approved these changes

2021-07-14 16:35 UTC, merged