VocSens added as new company.
TheThingsNetwork/lorawan-devices pull request #535
Opened 2022-09-21 10:30 UTC by njulemon

#### Summary
Added VocSens company & new device msem-10.

#### Changes
Added VocSens company & new device msem-10.

#### Notes for Reviewers
Ben Olayinka has been in touch with Bram Senave to add VocSens to device repo. 

#### Release Notes
First Time v-0.1

2022-09-21 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/lorawan-devices?pullRequest=535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/lorawan-devices?pullRequest=535) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/lorawan-devices?pullRequest=535) it.</sub>

2022-09-22 08:40 UTC, Jaime-Trinidad approved these changes

2022-10-01 12:11 UTC, Jaime-Trinidad commented
Hi @njulemon files need to be filled `index.yaml`  and  `msem-10.yaml`

2022-10-14 12:18 UTC, Jaime-Trinidad commented
@njulemon any update here?

2022-10-31 09:10 UTC, Jaime-Trinidad commented
Hi @njulemon please complete the files, so we can merge the devices. Thanks

2022-11-18 14:46 UTC, Jaime-Trinidad commented
Hi @njulemon any update?

2022-11-28 16:39 UTC, johanstokking requested changes
- Please add `vocsens` to `vendor/index.yaml`
- Please remove empty `vendor/vocsens/msem-10.yaml`
- Please address review comments

2022-11-28 16:39 UTC, johanstokking commented on vendor/vocsens/msem-10-profile-eu868.yaml
> +The codecs are defined in the Payload codec definition file, with the same filename as the codec ID: vendor/<vendor-id>/<codec>.yaml:
This should be commented, although it looks technically like valid YAML

2022-11-28 16:42 UTC, johanstokking commented
Ah it looks like everything is combined in one file. It should be split over end device, codec and profile files. See `vendor/example`.

2023-06-07 15:14 UTC, Jaime-Trinidad commented
Hi @njulemon I will close this PR due time.

2023-06-07 15:14 UTC, closed without merging