Added Arduino devices
TheThingsNetwork/lorawan-devices pull request #55
Opened 2021-01-12 15:13 UTC by karlsoderby

#### Summary

...

#### Changes

- Added MKR WAN 1310
- Added Arduino Pro Gateway LoRa®
- Added Portenta Vision Shield LoRa®

#### Notes for Reviewers

...

#### Release Notes

- ...

2021-01-12 15:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/lorawan-devices?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/lorawan-devices?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/lorawan-devices?pullRequest=55) it.</sub>

2021-01-13 09:26 UTC, johanstokking approved these changes
Great, just one remark for next time, thanks @karlsoderby

2021-01-13 09:26 UTC, johanstokking commented on vendor/arduino/index.yaml
> +# This example contains just one end device: windsensor. It is referenced here in the index.
You might want to remove this text here

2021-01-13 09:27 UTC, johanstokking requested changes
Oh wait... you're adding a gateway. That is not supported (yet).

Please remove the gateway, thanks!

2021-01-13 16:09 UTC, karlsoderby commented
Hi Johan! Thanks for approving, I will take a look first thing in the
morning and submit a new PR without the gateway!

On Wed, 13 Jan 2021 at 10:27, Johan Stokking <notifications@github.com>
wrote:

> *@johanstokking* requested changes on this pull request.
>
> Oh wait... you're adding a gateway. That is not supported (yet).
>
> Please remove the gateway, thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheThingsNetwork/lorawan-devices/pull/55#pullrequestreview-567033580>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIORUHPJ4TBNG6HYHX6UWR3SZVRQ7ANCNFSM4V7LI5CQ>
> .
>

2021-01-14 10:30 UTC, johanstokking approved these changes

2021-01-14 10:30 UTC, johanstokking commented
Thanks @karlsoderby !

2021-01-14 10:30 UTC, merged