milesight-iot add new sensor AM107
TheThingsNetwork/lorawan-devices pull request #69
Opened 2021-01-14 14:54 UTC by Milesight-IoT

Requested by: iot.support@milesight.com

Summary
Adds support for the Milesight-IoT AM107 sensor.

2021-01-14 14:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/lorawan-devices?pullRequest=69) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/lorawan-devices?pullRequest=69) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/lorawan-devices?pullRequest=69) it.</sub>

2021-01-15 01:09 UTC, harryhua1989 reviewed
all good.

2021-01-18 09:56 UTC, johanstokking requested changes

2021-01-18 09:56 UTC, johanstokking commented on vendor/index.yaml
> +    vendorID: 600
We keep https://lora-alliance.org/wp-content/uploads/2020/11/LoRa_Alliance_Vendor_ID_for_QR_Code.pdf as authoritive index. 600 is reserved for future use.

Were you a LoRa Alliance member before, and was this your ID?

2021-01-18 09:56 UTC, johanstokking commented on vendor/milesight-iot/profile-as923.yaml
> +vendorProfileID: 600
The idea here is that each profile has its unique index that is issued by the vendor.

The `vendorID` + `vendorProfileID` are globally unique. I see now that you use 600 for different profiles.

2021-01-18 10:16 UTC, harryhua1989 commented
Hello Johan,
Thanks for the comment

Our previous ID is 601, Ursalink Technology Co., Ltd., now we upgrade our brand to Milesight IoT Co., Ltd,  I suppose we can keep using 601 and using the new Company name.
If yes, I will publish the new document to github. 

Waiting for your reply.
Harry Hua
Field Application Engineer
Milesight IoT
4F, No.63-2, Wanghai Road, 2nd Software Park, Xiamen
361008, China
Tel: 86-592-5085280-6048
Ticket System: https://support.milesight-iot.com
Email: harry@milesight.com 
Skype: harry.milesight 
Mobile: (+86) 15260221327
        
 
From: Johan Stokking
Date: 2021-01-18 17:56
To: TheThingsNetwork/lorawan-devices
CC: harryhua1989; Comment
Subject: Re: [TheThingsNetwork/lorawan-devices] milesight-iot add new sensor AM107 (#69)
@johanstokking requested changes on this pull request.


In vendor/index.yaml:
> @@ -944,6 +944,10 @@ vendors:
     name: Boston Networks Limited
     vendorID: 598
 
+  - id: milesight-iot
+    name: Milesight IoT Co., Ltd.
+    vendorID: 600

We keep https://lora-alliance.org/wp-content/uploads/2020/11/LoRa_Alliance_Vendor_ID_for_QR_Code.pdf as authoritive index. 600 is reserved for future use.
Were you a LoRa Alliance member before, and was this your ID?


In vendor/milesight-iot/profile-as923.yaml:
> @@ -0,0 +1,8 @@
+vendorProfileID: 600

The idea here is that each profile has its unique index that is issued by the vendor.
The vendorID + vendorProfileID are globally unique. I see now that you use 600 for different profiles.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-18 16:40 UTC, johanstokking commented
> Our previous ID is 601, Ursalink Technology Co., Ltd., now we upgrade our brand to Milesight IoT Co., Ltd, I suppose we can keep using 601 and using the new Company name. If yes, I will publish the new document to github.

Thanks. In that case, you can rename 601 to the new name (and change the folder name).

2021-01-19 12:25 UTC, johanstokking approved these changes
Thanks a lot

2021-01-19 12:26 UTC, merged